# Generated by Django 4.0.2 on 2022-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('createdOn', models.DateField()),
                ('completionDate', models.DateField(null=True)),
                ('completionStatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
